Agones
capturcus/deadfish pull request #35
Opened 2020-11-21 23:21 UTC by capturcus

- included agones in the development docker image
- included agones in our build system
- added scripts for automating agones related tasks
- added a simple server module for communicating with agones
- added agones files for launching a single server or a 2 server fleet

2020-11-28 11:09 UTC, piodul requested changes
(reviewed c++ code for now, didn't look at the YAMLs)

2020-11-28 11:09 UTC, piodul commented on server/agones.hpp
> +}; // agones
Nit: missing endline

2020-11-28 11:09 UTC, piodul commented on server/agones.cpp
> +void DoHealth()
Make it `static`

2020-11-28 11:09 UTC, piodul commented on server/agones.cpp
> +void WatchUpdates()
Make it `static`

2020-11-28 11:09 UTC, piodul commented on server/agones.cpp
> +	health.join();
Doesn't this hang this thread? The `health` thread runs an infinite loop.

2020-11-28 11:09 UTC, piodul commented on server/agones.cpp
> +	health.join();
We should notify the `health` thread that we are stopping and that it should no longer be running. Here is a suggestion how to do it: https://stackoverflow.com/a/59756732/12851162

2020-11-28 11:09 UTC, piodul commented on server/main.cpp
> +		new std::thread(agones::Start);
🙄

2020-11-28 11:09 UTC, piodul commented on server/agones.cpp
> +void dfAgones::Start()
I don't think this function should be blocking. Its name suggests that it should return after Agones SDK's initialization finishes.

I'd move everything after line:

```c++
	std::cout << "GameServer name: " << gameserver.object_meta().name() << "\n"
			  << std::flush;
```

to the beginning of the `dfAgones::Shutdown()` function.

2020-11-28 11:09 UTC, piodul commented on server/agones.cpp
> +		exit(1);
IMO, the function `dfAgones::Start()` should return a boolean value indicating if we successfully started the server.

2020-12-20 21:06 UTC, capturcus commented
idea: agones::Start initializes the agones sdk and if it all succeeds launches the separate agones threads containing health checks and server state watches.
Add an atomic flag whether the additional threads should return.

2020-12-30 18:20 UTC, capturcus commented on server/agones.cpp
> +	health.join();
resolved this according to the comment below

2020-12-30 18:20 UTC, capturcus commented on server/main.cpp
> +		new std::thread(agones::Start);
resolved this according to the comment below

2020-12-30 18:20 UTC, capturcus commented on server/agones.cpp
> +void dfAgones::Start()
resolved this according to the comment below

2020-12-30 18:20 UTC, capturcus commented on server/agones.cpp
> +		exit(1);
resolved this according to the comment below

2020-12-30 22:57 UTC, piodul commented on server/agones.cpp
> +		std::cout << "GameServer Update:\n"								   //
Nit: There is an empty comment in this line, prepended by lots of whitespace characters

2021-01-24 08:56 UTC, piodul approved these changes

2021-01-30 10:40 UTC, merged